# docker-compose.yml content
version: '3.8'

services:
  ai-agent:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./documents:/app/documents
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STREAMLIT_AUTH_USERNAME=${STREAMLIT_AUTH_USERNAME}
      - STREAMLIT_AUTH_PASSWORD=${STREAMLIT_AUTH_PASSWORD}
